[project]
name = "python-tools"
version = "0.1.0"
dependencies = [
    "ruff>=0.1.6",
    "ruff-lsp>=0.0.45",
    "pyright>=1.1.336",
    "yamllint>=1.35.1",
    "sqlfluff>=3.0.7",
]
requires-python = ">= 3.12"
