completions:
  # tmux
  - name: tmux attach
    patterns:
      - "^tmux a -t $"
      - "^tmux attach -t $"
    sourceCommand: "tmux list-sessions -F '#{session_name}'"
    options:
      --prompt: "'tmux attach > '"
  - name: tmux kill-session
    patterns:
      - "^tmux kill-session -t $"
    sourceCommand: "tmux list-sessions -F '#{session_name}'"
    options:
      --prompt: "'tmux kill-session > '"

  # zellij
  - name: zellij attach
    patterns:
      - "^zellij a $"
      - "^zellij attach $"
    sourceCommand: "zellij list-sessions --short"
    options:
      --prompt: "'zellij attach > '"
  - name: zellij delete-session
    patterns:
      - "^zellij d $"
      - "^zellij delete-session $"
    sourceCommand: "zellij list-sessions --short"
    options:
      --prompt: "'zellij delete-session > '"
  - name: zellij layout
    patterns:
      - "^zellij --layout $"
    sourceCommand: |
      eza -1 ${XDG_CONFIG_HOME}/zellij/layouts | sed 's/\.[^.]*$//'
    options:
      --prompt: "'zellij layout > '"

snippets:
  # Shell
  - name: "null"
    keyword: "null"
    snippet: ">/dev/null 2>&1"
    context:
      lbuffer: '.+\s'
  - name: restart shell (login)
    keyword: rlsh
    snippet: exec $SHELL -l

  # Git
  - name: git status
    keyword: gs
    snippet: git status --short --branch

  # tmux
  - name: tmux
    keyword: t
    snippet: tmux
  - name: tmux list-sessions
    keyword: tls
    snippet: tmux list-sessions
  - name: tmux attach
    keyword: ta
    snippet: tmux attach -t
  - name: tmux kill-session
    keyword: tk
    snippet: tmux kill-session -t
  - name: tmux kill-session (all)
    keyword: tka
    snippet: tmux kill-session -a

  # zellij
  - name: zellij
    keyword: j
    snippet: zellij
  - name: zellij delete-all-sessions
    keyword: jda
    snippet: zellij delete-all-sessions --yes
  - name: zellij delete-session
    keyword: jd
    snippet: zellij delete-session
  - name: zellij run
    keyword: jr
    snippet: zellij run -c --
  - name: zellij list-sessions
    keyword: jls
    snippet: zellij list-sessions
  - name: zellij layout
    keyword: jl
    snippet: zellij --layout
  - name: zellj attach
    keyword: ja
    snippet: zellij attach
  - name: zellij delete
    keyword: jd
    snippet: zellij delete

  # convmv
  - name: "convmv (dryrun)"
    keyword: cmd
    snippet: convmv -f utf-8 -t utf-8 --nfc --nosmart -r .
  - name: "convmv (notest)"
    keyword: cmn
    snippet: convmv -f utf-8 -t utf-8 --nfc --nosmart -r . --notest

# # eza
# - name: list
#   keyword: ls
#   snippet: eza --icons --git
# - name: list long
#   keyword: ll
#   snippet: eza --icons --git -l
# - name: long list (sort) changed
#   keyword: llc
#   snippet: eza --icons --git -l -s changed
# - name: list all
#   keyword: la
#   snippet: eza --icons --git -a
# - name: list all long
#   keyword: lal
#   snippet: eza --icons --git -al
# - name: list all long (sort) changed
#   keyword: lalc
#   snippet: eza --icons --git -al -s changed
# - name: list tree
#   keyword: lt
#   snippet: eza -T -L 3 -a -I "node_modules|.git|.cache" --icons
# - name: list tree long
#   keyword: ltl
#   snippet: eza -T -L 3 -a -I "node_modules|.git|.cache" -l --icons
