git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
  branchLogCmd: git log --graph --color=always --pretty=format:'-> %Cred%h%Creset %s%n  %C(yellow)%d%Creset %C(bold blue)<%an>%Creset %C(cyan)[%ad]%Creset %Cgreen(%cr)%n' --abbrev-commit --date=format:'%Y/%m/%d %H:%M:%S' --
  allBranchesLogCmds:
    - git log --graph --color=always --pretty=format:'-> %Cred%h%Creset %s%n  %C(yellow)%d%Creset %C(bold blue)<%an>%Creset %C(cyan)[%ad]%Creset %Cgreen(%cr)%n' --abbrev-commit --date=format:'%Y/%m/%d %H:%M:%S' --
gui:
  nerdFontsVersion: "3"
