#!/usr/bin/env bash

source "$CONFIG_DIR/color.sh"
source "$CONFIG_DIR/icons.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"

sketchybar --hotload true

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=bottom \
    color=$COLOR_BG \
    height=32 \
    margin=10 \
    corner_radius=8 \
    blur_radius=30 \
    padding_left=4 \
    padding_right=4 \
    y_offset=2 \
    sticky=on

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
    padding_left=4
    padding_right=4

    # background.color=$COLOR_BG  #debug
    background.height=30
    background.corner_radius=5

    icon.font="0xProto Nerd Font:Regular:14.0"
    icon.align=center
    icon.color="$COLOR_CYAN"
    icon.padding_left=6
    icon.padding_right=2

    label.font="0xProto Nerd Font:Regular:14.0"
    label.color="$COLOR_FG"
    label.padding_left=2
    label.padding_right=6
)
sketchybar --default "${default[@]}"

##### Adding Mission Control Space Indicators #####
# Let's add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces.

# for i in "${!ICONS_SPACE[@]}"; do
#     sid="$((i + 1))"
#     space=(
#         space="$sid"
#         icon="${ICONS_SPACE[i]}"
#         icon.font.size=14
#         icon.y_offset=5
#         icon.padding_left=7
#         icon.padding_right=7
#         background.color=$COLOR_CYAN
#         background.corner_radius=5
#         background.height=3
#         background.y_offset=-12
#         script="$PLUGIN_DIR/app_space.sh"
#     )
#     sketchybar --add space space."$sid" left \
#         --set space."$sid" "${space[@]}" \
#         --subscribe space.$sid front_app_switched window_change
# done

sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
    space=(
        icon="${ICONS_SPACE[sid - 1]}"
        icon.font.size=18
        icon.y_offset=2
        icon.padding_left=7
        icon.padding_right=7
        label.drawing=off
        background.color="$COLOR_CYAN"
        background.corner_radius=5
        background.height=3
        background.y_offset=-12
        script="$PLUGIN_DIR/aerospace.sh $sid"
    )
    sketchybar --add item "space.$sid" left \
        --subscribe "space.$sid" aerospace_workspace_change \
        --set "space.$sid" "${space[@]}"
done

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

sketchybar --add item front_app center \
    --set front_app icon=󰍹 \
    padding_left=30 \
    label.padding_left=12 \
    label.padding_right=12 \
    script="$PLUGIN_DIR/front_app.sh" \
    --subscribe front_app front_app_switched

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right \
    --set clock update_freq=10 script="$PLUGIN_DIR/clock.sh" \
    \
    --add item volume right \
    --set volume script="$PLUGIN_DIR/volume.sh" \
    --subscribe volume volume_change \
    \
    --add item battery right \
    --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
    --subscribe battery system_woke power_source_change \
    \
    --add item slack right \
    --set slack update_freq=180 script="$PLUGIN_DIR/slack.sh" \
    --subscribe slack system_woke
# \
# --add item brew right \
# --set brew update_freq=43200 script="$PLUGIN_DIR/brew.sh" \
# --subscribe brew system_woke

# sketchybar --add item clock right \
#     --set clock update_freq=10 script="$PLUGIN_DIR/clock.sh" \
#     \
#     --add item volume right \
#     --set volume script="$PLUGIN_DIR/volume.sh" \
#     --subscribe volume volume_change \
#     \
#     --add item battery right \
#     --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
#     --subscribe battery system_woke power_source_change \
#     \
#     --add item org_clock right \
#     --set org_clock update_freq=600 script="$PLUGIN_DIR/org_clock.sh" \
#     --subscribe org_clock system_woke \
#     \
#     --add item org_deadline right \
#     --set org_deadline update_freq=600 script="$PLUGIN_DIR/org_deadline.sh" \
#     --subscribe org_deadline system_woke \
#     \
#     --add item org_scheduled right \
#     --set org_scheduled update_freq=600 script="$PLUGIN_DIR/org_scheduled.sh" \
#     --subscribe org_scheduled system_woke \
#     \
#     --add item org_total right \
#     --set org_total update_freq=600 script="$PLUGIN_DIR/org_total.sh" \
#     --subscribe org_total system_woke \
#     \
#     --add item org_plan right \
#     --set org_plan update_freq=600 script="$PLUGIN_DIR/org_plan.sh" \
#     --subscribe org_plan system_woke \
#     \
#     --add item slack right \
#     --set slack update_freq=180 script="$PLUGIN_DIR/slack.sh" \
#     --subscribe slack system_woke \
#     \
#     --add item brew right \
#     --set brew update_freq=43200 script="$PLUGIN_DIR/brew.sh" \
#     --subscribe brew system_woke

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
