name: Install Test (Ubuntu)

on:
  push:
    branches:
      - 'main'
    paths:
      - 'etc/Brewfile-Linux'
      - 'Makefile'
      - 'scripts/*'
  pull_request:
    paths:
      - 'etc/Brewfile-Linux'
      - 'Makefile'
      - 'scripts/*'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Update packages
        run: sudo apt-get update
      - name: Install required packages
        run: sudo apt-get install zsh
      - name: Install dotfiles
        run: make install
        shell: zsh {0}
      - name: Source zshenv
        run: source ~/.zshenv
        shell: zsh {0}
      - name: Clean dotfiles
        run: make clean
        shell: zsh {0}
