name: Install Test

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install required packages
        run: apt-get update && apt-get install -y build-essential procps curl file git sudo
      - name: Install dotfiles
        run: make test
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dotfiles
        run: make test
