name: Install Test

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install required packages
        run: sudo apt-get update
      - name: Install dotfiles
        run: make test
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dotfiles
        run: make test
